### ISSUE TITLE
[Suggestion] New Logo design for Pinstream

### ISSUE THREAD

**Issue by zularizal** [olliejm/Pinstream#1]
Hi @olliejm , I am a graphic designer. I want to help you in graphic design.

After I review your project, your logo looks simple and unattractive. So, I want to contribute to this project by creating a new logo and adaptive icons, it's free. What do you think?

**Comment by olliejm** [comment]
Sure I'm completely open to that! The current logo is really just a placeholder I quickly made in Android Studio using their own icons.

I was intending to get around to making one myself at some point but won't have the free time for a while now. Let me know what you come up with.

Cheers!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by linadesteem** [comment]
Hi, I also want to contribute to this project, here is my attemp to make Pinstream logo:

This is the main logo with the logotype, Yo can put this main logo in project website, or Playstore banner.
![image](https://user-images.githubusercontent.com/35618068/40438358-192049e8-5ee2-11e8-87b8-2780037634e1.png)

here is the icon version of it.
![image](https://user-images.githubusercontent.com/35618068/40438365-1e07a0e6-5ee2-11e8-8f19-bb0a89c978d3.png)

Pinstream app follow material style, so I made the logo in material style too. What do you think? if you like it, I will send PR, or maybe you want me to change the colour?

**Comment by zularizal** [comment]
What do you think? Which one do you like? And what color do you like? If you change, please feel free to let me know

![logo](https://user-images.githubusercontent.com/38547278/40570012-bec1d9dc-60b0-11e8-868c-930ce07a3851.png)
